name: Deploy
on:
  push:
    branches:
      - main
      - image
jobs:
  update-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - id: version
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: cat ./mfnf2serlo/version
          create-tag: false
  docker-image:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    needs: update-version
    if: ${{ needs.update-version.outputs.current-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_GH_ACTIONS_CREDENTIALS }}'
      - uses: google-github-actions/setup-gcloud@v1
      - run: ./mfnf2serlo/scripts/deploy_image.sh
